/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'colorTag' : IDL.Text,
  'iconEmoji' : IDL.Text,
});
export const Topic = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'subjectId' : IDL.Nat,
  'notes' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const Bookmark = IDL.Record({
  'userId' : IDL.Principal,
  'topicId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const RecentlyWatched = IDL.Record({
  'videoPositionSeconds' : IDL.Nat,
  'userId' : IDL.Principal,
  'watchedAt' : IDL.Int,
  'topicId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBookmark' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSubject' : IDL.Func([Subject], [], []),
  'createTopic' : IDL.Func([Topic], [], []),
  'deleteSubject' : IDL.Func([IDL.Nat], [], []),
  'deleteTopic' : IDL.Func([IDL.Nat], [], []),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getBookmarks' : IDL.Func([], [IDL.Vec(Bookmark)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRecentlyWatched' : IDL.Func([], [IDL.Vec(RecentlyWatched)], ['query']),
  'getTopicsBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Topic)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordRecentlyWatched' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'removeBookmark' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchTopicsByKeyword' : IDL.Func([IDL.Text], [IDL.Vec(Topic)], ['query']),
  'updateSubject' : IDL.Func([Subject], [], []),
  'updateTopic' : IDL.Func([Topic], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'colorTag' : IDL.Text,
    'iconEmoji' : IDL.Text,
  });
  const Topic = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'subjectId' : IDL.Nat,
    'notes' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const Bookmark = IDL.Record({
    'userId' : IDL.Principal,
    'topicId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const RecentlyWatched = IDL.Record({
    'videoPositionSeconds' : IDL.Nat,
    'userId' : IDL.Principal,
    'watchedAt' : IDL.Int,
    'topicId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBookmark' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSubject' : IDL.Func([Subject], [], []),
    'createTopic' : IDL.Func([Topic], [], []),
    'deleteSubject' : IDL.Func([IDL.Nat], [], []),
    'deleteTopic' : IDL.Func([IDL.Nat], [], []),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getBookmarks' : IDL.Func([], [IDL.Vec(Bookmark)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRecentlyWatched' : IDL.Func([], [IDL.Vec(RecentlyWatched)], ['query']),
    'getTopicsBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Topic)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordRecentlyWatched' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'removeBookmark' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchTopicsByKeyword' : IDL.Func([IDL.Text], [IDL.Vec(Topic)], ['query']),
    'updateSubject' : IDL.Func([Subject], [], []),
    'updateTopic' : IDL.Func([Topic], [], []),
  });
};

export const init = ({ IDL }) => { return []; };