/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bookmark { 'userId' : Principal, 'topicId' : bigint }
export interface RecentlyWatched {
  'videoPositionSeconds' : bigint,
  'userId' : Principal,
  'watchedAt' : bigint,
  'topicId' : bigint,
}
export interface Subject {
  'id' : bigint,
  'order' : bigint,
  'name' : string,
  'description' : string,
  'colorTag' : string,
  'iconEmoji' : string,
}
export interface Topic {
  'id' : bigint,
  'title' : string,
  'order' : bigint,
  'subjectId' : bigint,
  'notes' : string,
  'videoUrl' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBookmark' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSubject' : ActorMethod<[Subject], undefined>,
  'createTopic' : ActorMethod<[Topic], undefined>,
  'deleteSubject' : ActorMethod<[bigint], undefined>,
  'deleteTopic' : ActorMethod<[bigint], undefined>,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'getBookmarks' : ActorMethod<[], Array<Bookmark>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRecentlyWatched' : ActorMethod<[], Array<RecentlyWatched>>,
  'getTopicsBySubject' : ActorMethod<[bigint], Array<Topic>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordRecentlyWatched' : ActorMethod<[bigint, bigint], undefined>,
  'removeBookmark' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchTopicsByKeyword' : ActorMethod<[string], Array<Topic>>,
  'updateSubject' : ActorMethod<[Subject], undefined>,
  'updateTopic' : ActorMethod<[Topic], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];